In [1]:
import numpy as np

In [2]:
X=np.array([[1,-1,2],[2,0,0],[0,1,-1]])

In [3]:
from sklearn.preprocessing import scale

In [4]:
X_scaled=scale(X)

In [5]:
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [6]:
X_scaled.mean(axis=0)

array([0., 0., 0.])

In [7]:
X_scaled.std(axis=0)

array([1., 1., 1.])

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
Scaler=StandardScaler()

In [10]:
Scaler.fit(X)

StandardScaler()

In [11]:
Scaler.transform(X) #Same as X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])