# Forward Propagation:

In [1]:
import numpy as np

In [2]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[0,1,1,0]]).T
X.shape,Y.shape,X,Y

((4, 2),
 (4, 1),
 array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([[0],
        [1],
        [1],
        [0]]))

In [3]:
wh=2*np.random.random((2,2))-1
bh=2*np.random.random((1,2))-1
wo=2*np.random.random((2,1))-1
bo=2*np.random.random((1,1))-1

In [4]:
def sig(z):
    return 1/(1+np.exp(-z))

In [5]:
output0=X
outputHidden=sig(np.dot(output0,wh)+bh)
output=sig(np.dot(outputHidden,wo)+bo)
output

array([[0.27633565],
       [0.29838073],
       [0.27680034],
       [0.29962728]])

# Backward Propagation:

In [6]:
def derivateSig(z):
    return sig(z)*(1-sig(z))

In [7]:
lr=0.1 
for iter in range(10000):
    output0=X
    inputHidden=np.dot(output0,wh)+bh
    outputHidden=sig(inputHidden)
    inputForOutputLayer=np.dot(outputHidden,wo)+bo
    output=sig(inputForOutputLayer)
        
    first_term_output_layer=output-Y
    second_term_output_layer=derivateSig(inputForOutputLayer)
    first_two_output_layer=first_term_output_layer*second_term_output_layer
        
    first_term_hidden_layer=np.dot(first_two_output_layer,wo.T)
    second_term_hidden_layer=derivateSig(inputHidden)
    first_two_hidden_layer=first_term_hidden_layer*second_term_hidden_layer
        
    changes_output=np.dot(outputHidden.T,first_two_output_layer)
    changes_output_bias=np.sum(first_two_output_layer,axis=0,keepdims=True)
        
    changes_hidden=np.dot(output0.T,first_two_hidden_layer)
    changes_hidden_bias=np.sum(first_two_hidden_layer,axis=0,keepdims=True)
    
    wo=wo-lr*changes_output
    bo=bo-lr*changes_output_bias
    wh=wh-lr*changes_hidden
    bh=bh-lr*changes_hidden_bias

In [8]:
output0=X
inputHidden=np.dot(output0,wh)+bh
outputHidden=sig(inputHidden)
inputForOutputLayer=np.dot(outputHidden,wo)+bo
output=sig(inputForOutputLayer)
wo,bo,wh,bh,output

(array([[6.09379004],
        [6.35450752]]),
 array([[-9.05263046]]),
 array([[ 6.27611794, -3.88534758],
        [ 6.43083271, -3.90722473]]),
 array([[-2.70505394,  5.8024874 ]]),
 array([[0.08823948],
        [0.91849764],
        [0.91792153],
        [0.10020035]]))